name: GitHub Actions Demo
on:
  push:
    branches: [add-workflow]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
      - name: Initialize Terraform
        run: terraform init
      - name: Validate Terraform code
        run: terraform validate
      - name: Plan Terraform changes
        id: plan
        run: terraform plan -input=false -lock=false -no-color
      - name: Apply Terraform changes
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false -no-color
      - name: Show Terraform output
        run: terraform output -no-color
