name: GitHub Actions Demo

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.4
    - name: Initialize Terraform
      run: terraform init
    - name: Terraform Plan
      run: terraform plan -var name=$NAME
      env:
        NAME: ${{ github.event.inputs.name }}
    - name: Terraform Apply
      uses: ahmadnassri/action-terraform@v2.2.2
      with:
        args: apply -auto-approve -var name=$NAME
      env:
        NAME: ${{ github.event.inputs.name }}
    - name: Display Greeting
      run: echo ${{ steps.apply.outputs.greeting }}
      env:
        TF_STATE: ${{ steps.apply.outputs.tf_state }}
    - name: Destroy Terraform
      uses: ahmadnassri/action-terraform@v2.2.2
      with:
        args: destroy -auto-approve -var name=$NAME
      env:
        NAME: ${{ github.event.inputs.name }}
